# Generated by Django 4.2.11 on 2024-05-03 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DefaultGroup',
        ),
    ]
