# Generated by Django 4.2.11 on 2024-05-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='test', upload_to='media/avatars', verbose_name='photo de profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='fonction',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Assistant DAO'), (2, 'Chef Service Etude'), (3, 'Chef Departement Etude'), (4, 'Directeur Generale'), (5, 'admin'), (6, 'Coordinateur des Operations'), (7, 'Conducteurs des Travaux'), (8, 'Chef de Projet'), (9, 'DEGP'), (10, 'Magasinier'), (11, 'Intervenant')], null=True),
        ),
    ]
