# Generated by Django 4.2.11 on 2024-05-08 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_comment_parent_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='attachments/', verbose_name='Attachment')),
                ('file_type', models.CharField(choices=[('Photo', 'Photo'), ('Video', 'Video')], max_length=10, verbose_name='File type')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.post', verbose_name='Model that uses the image field')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
    ]
