# Generated by Django 4.2.11 on 2024-05-07 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_comment_parent_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='parent_post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='website.post'),
            preserve_default=False,
        ),
    ]
