# Generated by Django 4.2.11 on 2024-05-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_community_name_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='created_by',
            new_name='admin',
        ),
    ]
