# Generated by Django 4.2.11 on 2024-05-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_reaction_parent_comment_delete_commentreaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='parent_comment',
        ),
    ]
