# Generated by Django 4.2.11 on 2024-05-08 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_attachment_image_alter_attachment_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to='media/attachments/'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='parent_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='website.post'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='video',
            field=models.FileField(default=None, null=True, upload_to='media/attachments/'),
        ),
    ]
