# Generated by Django 4.2.11 on 2024-05-16 10:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0006_remove_commentupvote_parent_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='downvote',
            field=models.ManyToManyField(related_name='comment_downvotes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='upvote',
            field=models.ManyToManyField(related_name='comment_upvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
