# Generated by Django 4.2.11 on 2024-05-09 08:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0007_community_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(default=None, null=True, related_name='communities', to=settings.AUTH_USER_MODEL),
        ),
    ]
